name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: DEBUG: show env keys
        run: |
          echo "---- env keys containing AZURE_STATIC_WEB_APPS_API_TOKEN ----"
          env | grep AZURE_STATIC_WEB_APPS_API_TOKEN || true
          echo "---- list all AZURE_STATIC_WEB_APPS_* env vars ----"
          env | grep ^AZURE_STATIC_WEB_APPS || true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"         # root where your index.html lives
          api_location: ""          # empty because you currently have no /api folder
          output_location: "."
          app_build_command: ""     # explicitly disable any build step
